import type { Product, ProductCategory } from "./types";

// ── ~40 realistic products for the Champions Club Pro Shop ──

const IMG_PLACEHOLDER = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='400' fill='%231c2d4d'%3E%3Crect width='400' height='400'/%3E%3Ctext x='50%25' y='50%25' text-anchor='middle' dy='.35em' fill='%23d5f63a' font-family='sans-serif' font-size='48'%3E🏸%3C/text%3E%3C/svg%3E";

const p = (
  id: string,
  slug: string,
  name: string,
  brand: string,
  category: ProductCategory,
  sport: "tennis" | "padel" | "badminton" | "cricket-net",
  description: string,
  features: string[],
  basePrice: number,
  mrp: number,
  variantAxes: Product["variantAxes"],
  variants: Product["variants"],
  extra: Partial<Product> = {},
): Product => ({
  id,
  slug,
  name,
  brand,
  category,
  sport,
  description,
  features,
  basePrice,
  mrp,
  variantAxes,
  variants,
  images: [IMG_PLACEHOLDER],
  rating: 4 + Math.round(Math.random() * 10) / 10,
  reviewCount: 8 + Math.floor(Math.random() * 90),
  tags: [],
  ...extra,
});

export const SAMPLE_PRODUCTS: Product[] = [
  // ─── RACKETS ──────────────────────────────────────────────────────────
  p("PRD-001", "yonex-astrox-99-pro", "Yonex Astrox 99 Pro", "Yonex", "rackets", "badminton",
    "Head-heavy power racket with Namd graphite for explosive smashes. Preferred by international doubles players.",
    ["Namd graphite shaft", "Rotational Generator System", "Isometric head", "4U weight"],
    14999, 17990,
    [{ label: "Grip Size", options: ["G4", "G5"] }],
    [
      { id: "V-001A", sku: "YNX-AX99P-G4", axes: { "Grip Size": "G4" }, stock: 5, price: 14999 },
      { id: "V-001B", sku: "YNX-AX99P-G5", axes: { "Grip Size": "G5" }, stock: 3, price: 14999 },
    ],
    { isBestseller: true, tags: ["power", "advanced"] },
  ),
  p("PRD-002", "babolat-pure-aero", "Babolat Pure Aero 2024", "Babolat", "rackets", "tennis",
    "The ultimate spin machine. Features Aeromodular beam and FSI Power tech for devastating topspin.",
    ["300g unstrung", "Aeromodular beam", "FSI Power", "SWX Pure Feel"],
    22490, 24990,
    [{ label: "Grip Size", options: ["2", "3", "4"] }],
    [
      { id: "V-002A", sku: "BAB-PA24-G2", axes: { "Grip Size": "2" }, stock: 4, price: 22490 },
      { id: "V-002B", sku: "BAB-PA24-G3", axes: { "Grip Size": "3" }, stock: 6, price: 22490 },
      { id: "V-002C", sku: "BAB-PA24-G4", axes: { "Grip Size": "4" }, stock: 2, price: 22490 },
    ],
    { isNew: true, tags: ["spin", "advanced"] },
  ),
  p("PRD-003", "wilson-blade-98", "Wilson Blade 98 v9", "Wilson", "rackets", "tennis",
    "Control-oriented frame with unique Agiplast material for an enhanced feel. Tournament-level precision.",
    ["305g unstrung", "18×20 string pattern", "Agiplast", "Carbon mapping"],
    19999, 21990,
    [{ label: "Grip Size", options: ["2", "3"] }],
    [
      { id: "V-003A", sku: "WIL-BL98-G2", axes: { "Grip Size": "2" }, stock: 7, price: 19999 },
      { id: "V-003B", sku: "WIL-BL98-G3", axes: { "Grip Size": "3" }, stock: 3, price: 19999 },
    ],
    { tags: ["control", "advanced"] },
  ),
  p("PRD-004", "head-radical-mp", "Head Radical MP 2024", "Head", "rackets", "tennis",
    "Balanced powerhouse with Auxetic 2.0 construction and graphene 360+ tech.",
    ["295g unstrung", "16×19 pattern", "Auxetic 2.0", "Graphene 360+"],
    18990, 20990,
    [{ label: "Grip Size", options: ["2", "3", "4"] }],
    [
      { id: "V-004A", sku: "HEAD-RAD-G2", axes: { "Grip Size": "2" }, stock: 3, price: 18990 },
      { id: "V-004B", sku: "HEAD-RAD-G3", axes: { "Grip Size": "3" }, stock: 5, price: 18990 },
      { id: "V-004C", sku: "HEAD-RAD-G4", axes: { "Grip Size": "4" }, stock: 0, price: 18990 },
    ],
    { tags: ["balanced", "intermediate"] },
  ),
  p("PRD-005", "nox-ml10-pro", "NOX ML10 Pro Cup", "NOX", "rackets", "padel",
    "Professional padel racket with diamond shape and carbon frame for aggressive play.",
    ["Diamond shape", "Full carbon", "18K Aluminised", "360g ± 10g"],
    15999, 18490,
    [{ label: "Weight", options: ["355g", "365g"] }],
    [
      { id: "V-005A", sku: "NOX-ML10-355", axes: { Weight: "355g" }, stock: 4, price: 15999 },
      { id: "V-005B", sku: "NOX-ML10-365", axes: { Weight: "365g" }, stock: 2, price: 15999 },
    ],
    { isNew: true, tags: ["padel", "power"] },
  ),
  p("PRD-006", "li-ning-axforce-80", "Li-Ning Axforce 80", "Li-Ning", "rackets", "badminton",
    "Competition-grade badminton racket with dynamic optimum frame for maximum power transfer.",
    ["3U weight", "Dynamic Optimum Frame", "TB Nano", "Medium flex"],
    8999, 10990,
    [{ label: "Grip Size", options: ["S1", "S2"] }],
    [
      { id: "V-006A", sku: "LIN-AX80-S1", axes: { "Grip Size": "S1" }, stock: 8, price: 8999 },
      { id: "V-006B", sku: "LIN-AX80-S2", axes: { "Grip Size": "S2" }, stock: 6, price: 8999 },
    ],
    { tags: ["intermediate", "all-round"] },
  ),
  p("PRD-007", "yonex-nanoflare-700", "Yonex Nanoflare 700", "Yonex", "rackets", "badminton",
    "Speed-focused racket with Torayca M40X graphite for lightning-fast drives.",
    ["4U/5U weight", "Torayca M40X", "Sonic Flare System", "Stiff flex"],
    11499, 13990,
    [{ label: "Weight", options: ["4U", "5U"] }, { label: "Grip Size", options: ["G5", "G6"] }],
    [
      { id: "V-007A", sku: "YNX-NF700-4U-G5", axes: { Weight: "4U", "Grip Size": "G5" }, stock: 3, price: 11499 },
      { id: "V-007B", sku: "YNX-NF700-4U-G6", axes: { Weight: "4U", "Grip Size": "G6" }, stock: 4, price: 11499 },
      { id: "V-007C", sku: "YNX-NF700-5U-G5", axes: { Weight: "5U", "Grip Size": "G5" }, stock: 2, price: 11999 },
      { id: "V-007D", sku: "YNX-NF700-5U-G6", axes: { Weight: "5U", "Grip Size": "G6" }, stock: 1, price: 11999 },
    ],
    { isBestseller: true, tags: ["speed", "advanced"] },
  ),

  // ─── BALLS & SHUTTLES ────────────────────────────────────────────────
  p("PRD-010", "yonex-mavis-350", "Yonex Mavis 350", "Yonex", "balls", "badminton",
    "Premium nylon shuttles with consistent flight and durability. Medium speed for indoor play.",
    ["Nylon shuttle", "Medium speed", "6-pack tube", "Indoor play"],
    699, 799,
    [{ label: "Speed", options: ["Slow", "Medium", "Fast"] }],
    [
      { id: "V-010A", sku: "YNX-MV350-SLW", axes: { Speed: "Slow" }, stock: 20, price: 699 },
      { id: "V-010B", sku: "YNX-MV350-MED", axes: { Speed: "Medium" }, stock: 35, price: 699 },
      { id: "V-010C", sku: "YNX-MV350-FST", axes: { Speed: "Fast" }, stock: 15, price: 699 },
    ],
    { isBestseller: true, tags: ["training", "beginner"] },
  ),
  p("PRD-011", "wilson-us-open-tennis", "Wilson US Open Tennis Ball", "Wilson", "balls", "tennis",
    "Official ball of the US Open. ITF-approved felt with extra durability for hard court play.",
    ["3-ball can", "Extra Duty felt", "ITF approved", "Hard court"],
    599, 699,
    [{ label: "Pack", options: ["3 Balls", "4 Balls"] }],
    [
      { id: "V-011A", sku: "WIL-USO-3PK", axes: { Pack: "3 Balls" }, stock: 45, price: 599 },
      { id: "V-011B", sku: "WIL-USO-4PK", axes: { Pack: "4 Balls" }, stock: 30, price: 749 },
    ],
    { tags: ["match", "hard-court"] },
  ),
  p("PRD-012", "head-padel-pro", "Head Padel Pro Ball", "Head", "balls", "padel",
    "WPT-approved padel ball with controlled bounce and premium felt.",
    ["3-ball can", "WPT approved", "Premium felt", "Pressurised"],
    499, 599,
    [],
    [{ id: "V-012A", sku: "HEAD-PPB-3", axes: {}, stock: 50, price: 499 }],
    { tags: ["padel", "match"] },
  ),
  p("PRD-013", "yonex-aerosensa-50", "Yonex Aerosensa 50", "Yonex", "balls", "badminton",
    "Tournament-grade goose feather shuttlecocks. Used in BWF-sanctioned events.",
    ["12-pack tube", "Goose feather", "BWF approved", "Tournament grade"],
    2399, 2899,
    [{ label: "Speed", options: ["76", "77", "78"] }],
    [
      { id: "V-013A", sku: "YNX-AS50-76", axes: { Speed: "76" }, stock: 10, price: 2399 },
      { id: "V-013B", sku: "YNX-AS50-77", axes: { Speed: "77" }, stock: 18, price: 2399 },
      { id: "V-013C", sku: "YNX-AS50-78", axes: { Speed: "78" }, stock: 8, price: 2399 },
    ],
    { tags: ["tournament", "feather"] },
  ),
  p("PRD-014", "sg-club-cricket-ball", "SG Club Cricket Ball", "SG", "balls", "cricket-net",
    "Premium red leather cricket ball for net practice sessions. 4-piece construction.",
    ["Leather ball", "4-piece", "156g", "Red"],
    899, 1099,
    [],
    [{ id: "V-014A", sku: "SG-CLB-RED", axes: {}, stock: 25, price: 899 }],
    { tags: ["cricket", "practice"] },
  ),

  // ─── SHOES ────────────────────────────────────────────────────────────
  p("PRD-020", "yonex-power-cushion-65z", "Yonex Power Cushion 65 Z3", "Yonex", "shoes", "badminton",
    "Lightweight indoor court shoe with Power Cushion+ for shock absorption and quick movements.",
    ["Power Cushion+", "Round sole", "Lightweight", "Non-marking"],
    9499, 10990,
    [{ label: "Size", options: ["7", "8", "9", "10", "11"] }, { label: "Color", options: ["White/Red", "Black/Gold"] }],
    [
      { id: "V-020A", sku: "YNX-PC65Z-7-WR", axes: { Size: "7", Color: "White/Red" }, stock: 3, price: 9499 },
      { id: "V-020B", sku: "YNX-PC65Z-8-WR", axes: { Size: "8", Color: "White/Red" }, stock: 5, price: 9499 },
      { id: "V-020C", sku: "YNX-PC65Z-9-WR", axes: { Size: "9", Color: "White/Red" }, stock: 4, price: 9499 },
      { id: "V-020D", sku: "YNX-PC65Z-10-WR", axes: { Size: "10", Color: "White/Red" }, stock: 2, price: 9499 },
      { id: "V-020E", sku: "YNX-PC65Z-9-BG", axes: { Size: "9", Color: "Black/Gold" }, stock: 3, price: 9499 },
      { id: "V-020F", sku: "YNX-PC65Z-10-BG", axes: { Size: "10", Color: "Black/Gold" }, stock: 1, price: 9499 },
    ],
    { isBestseller: true, tags: ["court-shoe", "indoor"] },
  ),
  p("PRD-021", "asics-gel-resolution-9", "Asics Gel Resolution 9", "Asics", "shoes", "tennis",
    "Premium all-court tennis shoe with GEL cushioning and DYNAWRAP upper for secure lockdown.",
    ["GEL technology", "DYNAWRAP", "AHAR outsole", "All-court"],
    11999, 13990,
    [{ label: "Size", options: ["8", "9", "10", "11"] }, { label: "Color", options: ["White/Blue", "Black/Volt"] }],
    [
      { id: "V-021A", sku: "ASC-GR9-8-WB", axes: { Size: "8", Color: "White/Blue" }, stock: 4, price: 11999 },
      { id: "V-021B", sku: "ASC-GR9-9-WB", axes: { Size: "9", Color: "White/Blue" }, stock: 6, price: 11999 },
      { id: "V-021C", sku: "ASC-GR9-10-WB", axes: { Size: "10", Color: "White/Blue" }, stock: 3, price: 11999 },
      { id: "V-021D", sku: "ASC-GR9-9-BV", axes: { Size: "9", Color: "Black/Volt" }, stock: 2, price: 11999 },
      { id: "V-021E", sku: "ASC-GR9-10-BV", axes: { Size: "10", Color: "Black/Volt" }, stock: 0, price: 11999 },
    ],
    { tags: ["all-court", "durable"] },
  ),
  p("PRD-022", "nike-vapor-pro-2", "Nike Court Air Zoom Vapor Pro 2", "Nike", "shoes", "tennis",
    "Tour-level tennis shoe featuring Zoom Air unit and modified herringbone outsole.",
    ["Zoom Air", "Modified herringbone", "Lightweight mesh", "Clay/Hard court"],
    13499, 14995,
    [{ label: "Size", options: ["8", "9", "10", "11"] }],
    [
      { id: "V-022A", sku: "NIK-VP2-8", axes: { Size: "8" }, stock: 2, price: 13499 },
      { id: "V-022B", sku: "NIK-VP2-9", axes: { Size: "9" }, stock: 4, price: 13499 },
      { id: "V-022C", sku: "NIK-VP2-10", axes: { Size: "10" }, stock: 3, price: 13499 },
      { id: "V-022D", sku: "NIK-VP2-11", axes: { Size: "11" }, stock: 1, price: 13499 },
    ],
    { isNew: true, tags: ["premium", "clay-court"] },
  ),

  // ─── APPAREL ──────────────────────────────────────────────────────────
  p("PRD-030", "champions-club-polo", "Champions Club Training Polo", "Champions Club", "apparel", "tennis",
    "Official club polo with moisture-wicking DryFit fabric and embroidered club crest.",
    ["DryFit fabric", "Club crest", "Anti-odour", "Slim fit"],
    1999, 2499,
    [{ label: "Size", options: ["S", "M", "L", "XL", "XXL"] }, { label: "Color", options: ["Navy", "White", "Lime"] }],
    [
      { id: "V-030A", sku: "CC-POLO-S-NVY", axes: { Size: "S", Color: "Navy" }, stock: 8, price: 1999 },
      { id: "V-030B", sku: "CC-POLO-M-NVY", axes: { Size: "M", Color: "Navy" }, stock: 12, price: 1999 },
      { id: "V-030C", sku: "CC-POLO-L-NVY", axes: { Size: "L", Color: "Navy" }, stock: 10, price: 1999 },
      { id: "V-030D", sku: "CC-POLO-XL-NVY", axes: { Size: "XL", Color: "Navy" }, stock: 6, price: 1999 },
      { id: "V-030E", sku: "CC-POLO-M-WHT", axes: { Size: "M", Color: "White" }, stock: 9, price: 1999 },
      { id: "V-030F", sku: "CC-POLO-L-WHT", axes: { Size: "L", Color: "White" }, stock: 7, price: 1999 },
      { id: "V-030G", sku: "CC-POLO-M-LME", axes: { Size: "M", Color: "Lime" }, stock: 5, price: 1999 },
      { id: "V-030H", sku: "CC-POLO-L-LME", axes: { Size: "L", Color: "Lime" }, stock: 4, price: 1999 },
    ],
    { isBestseller: true, tags: ["club-branded", "training"] },
  ),
  p("PRD-031", "yonex-tournament-shorts", "Yonex Tournament Shorts", "Yonex", "apparel", "badminton",
    "Lightweight tournament shorts with stretch fabric and built-in ball pocket.",
    ["Stretch fabric", "Ball pocket", "Quick-dry", "Drawstring waist"],
    1799, 2199,
    [{ label: "Size", options: ["S", "M", "L", "XL"] }, { label: "Color", options: ["Black", "Navy"] }],
    [
      { id: "V-031A", sku: "YNX-SHRT-S-BLK", axes: { Size: "S", Color: "Black" }, stock: 6, price: 1799 },
      { id: "V-031B", sku: "YNX-SHRT-M-BLK", axes: { Size: "M", Color: "Black" }, stock: 10, price: 1799 },
      { id: "V-031C", sku: "YNX-SHRT-L-BLK", axes: { Size: "L", Color: "Black" }, stock: 8, price: 1799 },
      { id: "V-031D", sku: "YNX-SHRT-M-NVY", axes: { Size: "M", Color: "Navy" }, stock: 5, price: 1799 },
      { id: "V-031E", sku: "YNX-SHRT-L-NVY", axes: { Size: "L", Color: "Navy" }, stock: 4, price: 1799 },
    ],
    { tags: ["training", "tournament"] },
  ),
  p("PRD-032", "champions-wristband-set", "Champions Club Wristband Set", "Champions Club", "apparel", "tennis",
    "Cotton-blend wristband and headband set with embroidered club logo.",
    ["Cotton-blend", "Sweat-absorbing", "Club logo", "One size"],
    499, 699,
    [{ label: "Color", options: ["White", "Navy", "Lime"] }],
    [
      { id: "V-032A", sku: "CC-WB-WHT", axes: { Color: "White" }, stock: 20, price: 499 },
      { id: "V-032B", sku: "CC-WB-NVY", axes: { Color: "Navy" }, stock: 15, price: 499 },
      { id: "V-032C", sku: "CC-WB-LME", axes: { Color: "Lime" }, stock: 12, price: 499 },
    ],
    { tags: ["club-branded", "accessory"] },
  ),

  // ─── GRIPS & OVERWRAPS ────────────────────────────────────────────────
  p("PRD-040", "yonex-super-grap", "Yonex Super Grap Overgrip", "Yonex", "grips", "badminton",
    "Ultra-thin overgrip with excellent sweat absorption. Tour player favourite.",
    ["0.6mm thickness", "3-pack", "Anti-slip", "Moisture absorbing"],
    349, 449,
    [{ label: "Color", options: ["White", "Black", "Yellow"] }],
    [
      { id: "V-040A", sku: "YNX-SG-WHT", axes: { Color: "White" }, stock: 40, price: 349 },
      { id: "V-040B", sku: "YNX-SG-BLK", axes: { Color: "Black" }, stock: 35, price: 349 },
      { id: "V-040C", sku: "YNX-SG-YLW", axes: { Color: "Yellow" }, stock: 25, price: 349 },
    ],
    { isBestseller: true, tags: ["essential", "grip"] },
  ),
  p("PRD-041", "wilson-pro-overgrip", "Wilson Pro Overgrip", "Wilson", "grips", "tennis",
    "The world's #1 selling overgrip. Ultra-thin and absorbent.",
    ["3-pack", "0.5mm thin", "WTA/ATP favourite", "Ultra absorbent"],
    399, 499,
    [{ label: "Color", options: ["White", "Black"] }],
    [
      { id: "V-041A", sku: "WIL-POG-WHT", axes: { Color: "White" }, stock: 30, price: 399 },
      { id: "V-041B", sku: "WIL-POG-BLK", axes: { Color: "Black" }, stock: 22, price: 399 },
    ],
    { tags: ["essential", "overgrip"] },
  ),

  // ─── STRINGS ──────────────────────────────────────────────────────────
  p("PRD-050", "yonex-bg65", "Yonex BG65 String", "Yonex", "strings", "badminton",
    "The most popular badminton string in the world. Excellent durability and repulsion.",
    ["0.70mm gauge", "Nylon multifilament", "10m reel", "Durable"],
    299, 399,
    [{ label: "Color", options: ["White", "Blue", "Yellow"] }],
    [
      { id: "V-050A", sku: "YNX-BG65-WHT", axes: { Color: "White" }, stock: 50, price: 299 },
      { id: "V-050B", sku: "YNX-BG65-BLU", axes: { Color: "Blue" }, stock: 35, price: 299 },
      { id: "V-050C", sku: "YNX-BG65-YLW", axes: { Color: "Yellow" }, stock: 20, price: 299 },
    ],
    { isBestseller: true, tags: ["essential", "durable"] },
  ),
  p("PRD-051", "luxilon-alu-power", "Luxilon ALU Power", "Luxilon", "strings", "tennis",
    "The #1 string on the ATP Tour. Aluminium-infused co-polyester for control and spin.",
    ["1.25mm gauge", "Co-polyester", "12m set", "Spin & control"],
    1499, 1799,
    [{ label: "Gauge", options: ["1.20mm", "1.25mm", "1.30mm"] }],
    [
      { id: "V-051A", sku: "LUX-ALP-120", axes: { Gauge: "1.20mm" }, stock: 10, price: 1499 },
      { id: "V-051B", sku: "LUX-ALP-125", axes: { Gauge: "1.25mm" }, stock: 15, price: 1499 },
      { id: "V-051C", sku: "LUX-ALP-130", axes: { Gauge: "1.30mm" }, stock: 8, price: 1499 },
    ],
    { tags: ["pro-tour", "control"] },
  ),

  // ─── BAGS ─────────────────────────────────────────────────────────────
  p("PRD-060", "yonex-pro-9-racket-bag", "Yonex Pro 9 Racket Bag", "Yonex", "bags", "badminton",
    "Tournament bag with 3 compartments, thermal lining, and backpack straps.",
    ["3 compartments", "Thermal lining", "Backpack straps", "Shoe pocket"],
    5999, 7490,
    [{ label: "Color", options: ["Black", "Navy/Red"] }],
    [
      { id: "V-060A", sku: "YNX-PRO9-BLK", axes: { Color: "Black" }, stock: 4, price: 5999 },
      { id: "V-060B", sku: "YNX-PRO9-NR", axes: { Color: "Navy/Red" }, stock: 3, price: 5999 },
    ],
    { tags: ["tournament", "large"] },
  ),
  p("PRD-061", "wilson-super-tour-backpack", "Wilson Super Tour Backpack", "Wilson", "bags", "tennis",
    "Compact backpack with thermoguard and space for 2 rackets.",
    ["2-racket capacity", "Thermoguard", "Padded straps", "Accessory pocket"],
    4499, 5490,
    [{ label: "Color", options: ["Black/Green", "Navy"] }],
    [
      { id: "V-061A", sku: "WIL-STB-BG", axes: { Color: "Black/Green" }, stock: 5, price: 4499 },
      { id: "V-061B", sku: "WIL-STB-NVY", axes: { Color: "Navy" }, stock: 3, price: 4499 },
    ],
    { tags: ["backpack", "compact"] },
  ),

  // ─── ACCESSORIES ──────────────────────────────────────────────────────
  p("PRD-070", "yonex-vibration-stopper", "Yonex Vibration Stopper", "Yonex", "accessories", "tennis",
    "Compact vibration dampener for comfortable string bed feel.",
    ["2-pack", "Silicone", "Compact design", "Easy install"],
    199, 299,
    [{ label: "Color", options: ["Black", "Red", "Blue"] }],
    [
      { id: "V-070A", sku: "YNX-VS-BLK", axes: { Color: "Black" }, stock: 30, price: 199 },
      { id: "V-070B", sku: "YNX-VS-RED", axes: { Color: "Red" }, stock: 25, price: 199 },
      { id: "V-070C", sku: "YNX-VS-BLU", axes: { Color: "Blue" }, stock: 20, price: 199 },
    ],
    { tags: ["essential", "dampener"] },
  ),
  p("PRD-071", "champions-towel", "Champions Club Sports Towel", "Champions Club", "accessories", "tennis",
    "Quick-dry microfibre sports towel with embroidered club logo. 40×80cm.",
    ["Microfibre", "Quick-dry", "Club logo", "40×80cm"],
    799, 999,
    [{ label: "Color", options: ["Navy", "White"] }],
    [
      { id: "V-071A", sku: "CC-TWL-NVY", axes: { Color: "Navy" }, stock: 15, price: 799 },
      { id: "V-071B", sku: "CC-TWL-WHT", axes: { Color: "White" }, stock: 12, price: 799 },
    ],
    { tags: ["club-branded", "essential"] },
  ),
  p("PRD-072", "yonex-sports-bottle", "Yonex Sports Bottle 750ml", "Yonex", "accessories", "badminton",
    "BPA-free sports bottle with leak-proof lid and measuring marks.",
    ["750ml", "BPA-free", "Leak-proof", "Measuring marks"],
    599, 799,
    [{ label: "Color", options: ["Black", "Blue"] }],
    [
      { id: "V-072A", sku: "YNX-BTL-BLK", axes: { Color: "Black" }, stock: 18, price: 599 },
      { id: "V-072B", sku: "YNX-BTL-BLU", axes: { Color: "Blue" }, stock: 10, price: 599 },
    ],
    { tags: ["hydration", "essential"] },
  ),
  p("PRD-073", "kookaburra-bat-grip-cone", "Kookaburra Bat Grip Cone", "Kookaburra", "accessories", "cricket-net",
    "Professional bat grip applicator cone for easy cricket bat regripping.",
    ["Durable plastic", "Easy application", "Universal fit"],
    249, 349,
    [],
    [{ id: "V-073A", sku: "KOO-GRIP-CONE", axes: {}, stock: 12, price: 249 }],
    { tags: ["cricket", "tool"] },
  ),
  p("PRD-074", "champions-sweat-band", "Champions Club Headband", "Champions Club", "accessories", "tennis",
    "Moisture-wicking headband with club branding. Keeps sweat out of your eyes.",
    ["Elasticated", "Sweat-wicking", "Club logo", "One size"],
    299, 399,
    [{ label: "Color", options: ["White", "Black", "Lime"] }],
    [
      { id: "V-074A", sku: "CC-HB-WHT", axes: { Color: "White" }, stock: 20, price: 299 },
      { id: "V-074B", sku: "CC-HB-BLK", axes: { Color: "Black" }, stock: 15, price: 299 },
      { id: "V-074C", sku: "CC-HB-LME", axes: { Color: "Lime" }, stock: 10, price: 299 },
    ],
    { tags: ["club-branded", "accessory"] },
  ),
];

export function getProductBySlug(slug: string): Product | undefined {
  return SAMPLE_PRODUCTS.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return SAMPLE_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return SAMPLE_PRODUCTS.filter((p) => p.category === category);
}

export function getProductsBySport(sport: string): Product[] {
  return SAMPLE_PRODUCTS.filter((p) => p.sport === sport);
}

export function getFeaturedProducts(): Product[] {
  return SAMPLE_PRODUCTS.filter((p) => p.isBestseller || p.isNew).slice(0, 8);
}

export function getTotalStock(product: Product): number {
  return product.variants.reduce((sum, v) => sum + v.stock, 0);
}
