import { useState } from "react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { useAdminConfigStore } from "../adminConfigStore";
import {
  Building2,
  UploadCloud,
  FileCheck,
  ShieldCheck,
  Save,
  Globe,
  Mail,
  Phone,
  MapPin,
  Clock,
  Receipt,
  FileText,
  AlertCircle,
} from "lucide-react";
import { toast } from "@/components/ui/Toast";

export default function AdminClubProfilePage() {
  const { profile, updateProfile } = useAdminConfigStore();

  const [formData, setFormData] = useState({ ...profile });
  const [logoPreview, setLogoPreview] = useState<string>(profile.logoUrl);
  const [isSaving, setIsSaving] = useState(false);

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const fakeUrl = URL.createObjectURL(file);
      setLogoPreview(fakeUrl);
      setFormData((prev) => ({ ...prev, logoUrl: fakeUrl }));
      toast.success("Logo uploaded and preview generated!");
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    setTimeout(() => {
      updateProfile(formData);
      setIsSaving(false);
    }, 400);
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Club Profile & Legal Entity"
        subtitle="Manage brand assets, official tax GSTIN registration, physical address, and statutory gap-free invoice series."
      />

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Entity Brand & Logo Section */}
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <Card className="p-6 bg-court-500 border-white/14 lg:col-span-1">
            <h3 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
              <Building2 className="size-4 text-volt-400" />
              <span>Brand Emblem & Logo</span>
            </h3>

            <div className="flex flex-col items-center justify-center p-6 rounded-2xl bg-white/5 border-2 border-dashed border-white/20 text-center">
              {logoPreview ? (
                <div className="relative group mb-3">
                  <img
                    src={logoPreview}
                    alt="Club Logo"
                    className="size-24 rounded-2xl object-contain bg-navy-900/60 p-2 border border-white/20 shadow-md"
                  />
                  <div className="absolute inset-0 bg-navy-950/60 rounded-2xl opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity text-xs font-semibold text-volt-400">
                    Replace
                  </div>
                </div>
              ) : (
                <UploadCloud className="size-12 text-white/40 mb-3" />
              )}

              <p className="text-xs text-white/80 font-medium">PNG, SVG or WEBP (Max 2MB)</p>
              <p className="text-[11px] text-white/50 mt-1">Rendered on invoices, cards & nav</p>

              <label className="mt-4 cursor-pointer">
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleLogoUpload}
                  className="hidden"
                />
                <span className="inline-flex h-9 items-center gap-2 px-4 rounded-pill bg-white/10 hover:bg-white/16 border border-white/20 text-xs font-medium text-white transition-colors">
                  <UploadCloud className="size-3.5" />
                  <span>Choose File</span>
                </span>
              </label>
            </div>

            <div className="mt-4 p-3 rounded-xl bg-white/5 border border-white/10 text-[11px] text-white/60 space-y-1">
              <p className="font-semibold text-white/80 flex items-center gap-1.5">
                <ShieldCheck className="size-3.5 text-volt-400" />
                GST Compliant Output
              </p>
              <p>This logo and address appear on all official GST tax invoices generated by CCMS.</p>
            </div>
          </Card>

          {/* Core Entity Information */}
          <Card className="p-6 bg-court-500 border-white/14 lg:col-span-2 space-y-4">
            <h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2">
              <FileCheck className="size-4 text-emerald-400" />
              <span>Official Registration & Contacts</span>
            </h3>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Input
                label="Official Club Name *"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                required
              />
              <Input
                label="Club Tagline"
                value={formData.tagline}
                onChange={(e) => setFormData({ ...formData, tagline: e.target.value })}
              />
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <Input
                label="Statutory GSTIN *"
                value={formData.gstin}
                onChange={(e) => setFormData({ ...formData, gstin: e.target.value })}
                required
              />
              <Input
                label="Contact Phone *"
                value={formData.phone}
                onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                required
              />
              <Input
                label="Official Email *"
                type="email"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                required
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-white/80 mb-1.5">
                Registered Physical Address *
              </label>
              <textarea
                rows={2}
                value={formData.address}
                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                className="w-full p-3 rounded-xl bg-white/8 border border-white/18 text-xs text-white placeholder-white/40 focus:outline-none focus:border-volt-400"
                required
              />
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <Input
                label="City *"
                value={formData.city}
                onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                required
              />
              <Input
                label="State *"
                value={formData.state}
                onChange={(e) => setFormData({ ...formData, state: e.target.value })}
                required
              />
              <Input
                label="PIN Code *"
                value={formData.pincode}
                onChange={(e) => setFormData({ ...formData, pincode: e.target.value })}
                required
              />
            </div>

            {/* Timezone & Currency (Disabled/Fixed per Indian Club spec) */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 pt-2 border-t border-white/10">
              <div>
                <label className="block text-xs font-medium text-white/80 mb-1.5 flex items-center gap-1.5">
                  <Clock className="size-3.5 text-white/50" />
                  Operating Timezone (Locked)
                </label>
                <input
                  type="text"
                  value="Asia/Kolkata (IST +05:30)"
                  disabled
                  className="w-full h-11 px-3 rounded-xl bg-white/5 border border-white/10 text-xs text-white/50 cursor-not-allowed"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-white/80 mb-1.5">
                  Statutory Accounting Currency (Locked)
                </label>
                <input
                  type="text"
                  value="INR (₹) Indian Rupee"
                  disabled
                  className="w-full h-11 px-3 rounded-xl bg-white/5 border border-white/10 text-xs text-white/50 cursor-not-allowed"
                />
              </div>
            </div>
          </Card>
        </div>

        {/* Invoice and Billing Series Section */}
        <Card className="p-6 bg-court-500 border-white/14 space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-white/10">
            <div>
              <h3 className="text-base font-semibold text-white flex items-center gap-2">
                <Receipt className="size-4 text-volt-400" />
                <span>Statutory Gap-Free Number Series</span>
              </h3>
              <p className="text-xs text-white/70 mt-0.5">
                Indian GST compliance requires strictly sequential, gap-free invoice number prefixes.
              </p>
            </div>
            <span className="text-[11px] font-mono text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1 rounded-full">
              Audit Rule 46 Compliant
            </span>
          </div>

          <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
            {/* Invoice Series */}
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-3">
              <span className="text-xs font-bold uppercase tracking-wider text-volt-400">
                Customer Sales Tax Invoices
              </span>

              <div className="grid grid-cols-2 gap-3">
                <Input
                  label="Invoice Prefix *"
                  value={formData.invoicePrefix}
                  onChange={(e) => setFormData({ ...formData, invoicePrefix: e.target.value })}
                  required
                />
                <Input
                  label="Next Sequence Number *"
                  type="number"
                  value={formData.nextInvoiceNumber}
                  onChange={(e) =>
                    setFormData({ ...formData, nextInvoiceNumber: Number(e.target.value) })
                  }
                  required
                />
              </div>

              <div className="p-3 rounded-xl bg-court-700/80 border border-white/10 text-xs text-white/80">
                <span className="text-white/50 block text-[11px]">Next Issued Invoice Preview:</span>
                <span className="font-mono text-sm font-bold text-volt-400">
                  {formData.invoicePrefix}
                  {String(formData.nextInvoiceNumber).padStart(4, "0")}
                </span>
              </div>
            </div>

            {/* Vendor Bills Series */}
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-3">
              <span className="text-xs font-bold uppercase tracking-wider text-blue-400">
                Vendor Inward Bills Reference
              </span>

              <div className="grid grid-cols-2 gap-3">
                <Input
                  label="Bill Series Prefix *"
                  value={formData.billPrefix}
                  onChange={(e) => setFormData({ ...formData, billPrefix: e.target.value })}
                  required
                />
                <Input
                  label="Next Bill Sequence *"
                  type="number"
                  value={formData.nextBillNumber}
                  onChange={(e) =>
                    setFormData({ ...formData, nextBillNumber: Number(e.target.value) })
                  }
                  required
                />
              </div>

              <div className="p-3 rounded-xl bg-court-700/80 border border-white/10 text-xs text-white/80">
                <span className="text-white/50 block text-[11px]">Next Internal Voucher Preview:</span>
                <span className="font-mono text-sm font-bold text-blue-400">
                  {formData.billPrefix}
                  {String(formData.nextBillNumber).padStart(4, "0")}
                </span>
              </div>
            </div>
          </div>

          <div>
            <label className="block text-xs font-medium text-white/80 mb-1.5">
              Receipt & Invoice Footer Terms Note
            </label>
            <textarea
              rows={2}
              value={formData.receiptFooterNote}
              onChange={(e) => setFormData({ ...formData, receiptFooterNote: e.target.value })}
              className="w-full p-3 rounded-xl bg-white/8 border border-white/18 text-xs text-white placeholder-white/40 focus:outline-none focus:border-volt-400"
            />
          </div>
        </Card>

        {/* Submit Actions */}
        <div className="flex items-center justify-end gap-3 pt-2">
          <Button type="submit" variant="primary" loading={isSaving} className="gap-2 px-8">
            <Save className="size-4" />
            <span>Save Profile & Billing Series</span>
          </Button>
        </div>
      </form>
    </div>
  );
}
