-- V11: additive integrity and query optimizations for the existing CCMS model.
--
-- The optimized-schema proposal merged several existing domains (shop/bar/catalog,
-- orders, and notification delivery).  Those are not renamed here: this project has
-- live JPA entities, repositories and APIs for each table.  This migration preserves
-- that contract and adds only backward-compatible database improvements.

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Fast, club-local day lookups for member booking limits and court calendars.
-- These columns are generated by PostgreSQL; application code must not write them.
ALTER TABLE booking
    ADD COLUMN IF NOT EXISTS booking_day DATE GENERATED ALWAYS AS
        ((start_time AT TIME ZONE 'Asia/Kolkata')::date) STORED,
    ADD COLUMN IF NOT EXISTS start_slot SMALLINT GENERATED ALWAYS AS
        ((EXTRACT(HOUR FROM (start_time AT TIME ZONE 'Asia/Kolkata'))::int * 2
          + EXTRACT(MINUTE FROM (start_time AT TIME ZONE 'Asia/Kolkata'))::int / 30)::smallint) STORED;

ALTER TABLE booking
    ADD CONSTRAINT booking_start_slot_chk CHECK (start_slot BETWEEN 0 AND 47);

CREATE INDEX IF NOT EXISTS booking_member_day_active_idx
    ON booking (member_id, booking_day)
    WHERE status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'NO_SHOW');

CREATE INDEX IF NOT EXISTS booking_court_day_active_idx
    ON booking (court_id, booking_day)
    WHERE status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'NO_SHOW');

CREATE INDEX IF NOT EXISTS membership_expiry_active_idx
    ON membership (end_date)
    WHERE status IN ('ACTIVE', 'EXPIRING_SOON');

CREATE INDEX IF NOT EXISTS social_session_court_time_idx
    ON social_session (court_id, start_at)
    WHERE status IN ('OPEN', 'FULL');

CREATE INDEX IF NOT EXISTS social_participant_session_status_joined_idx
    ON social_participant (session_id, status, joined_at);

CREATE INDEX IF NOT EXISTS waitlist_court_slot_waiting_idx
    ON waitlist (court_id, requested_start_at, position)
    WHERE status = 'WAITING' AND court_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS follow_up_open_due_idx
    ON follow_up (due_at)
    WHERE status IN ('OPEN', 'OVERDUE');

CREATE INDEX IF NOT EXISTS payment_paid_ledger_idx
    ON payment (paid_at, source_type, method)
    WHERE status = 'PAID';

-- A gateway callback/retry must never create the same external payment twice.
CREATE UNIQUE INDEX IF NOT EXISTS payment_gateway_transaction_uq
    ON payment (gateway, gateway_transaction_id)
    WHERE gateway IS NOT NULL AND gateway_transaction_id IS NOT NULL;

-- Payroll can have only one payslip for a given employee in a monthly run.
CREATE UNIQUE INDEX IF NOT EXISTS payslip_run_employee_uq
    ON payslip (payroll_run_id, employee_id);

-- PostgreSQL is the final cross-node guard for court occupancy.  The service-level
-- locks remain the fast path; only active periods participate in this constraint.
ALTER TABLE occupancy
    ADD CONSTRAINT occupancy_no_overlapping_active_periods
    EXCLUDE USING gist (court_id WITH =, occupied_period WITH &&)
    WHERE (status = 'ACTIVE');
