-- V19: Bar module refined tables, sequences and columns

CREATE SEQUENCE IF NOT EXISTS bar_order_no_seq START WITH 1000;

CREATE TABLE IF NOT EXISTS bar_tab (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    member_id UUID REFERENCES member(id) ON DELETE SET NULL,
    guest_name VARCHAR(255),
    table_id UUID REFERENCES bar_table(id) ON DELETE SET NULL,
    opened_by UUID REFERENCES app_user(id) ON DELETE SET NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    limit_amount NUMERIC(12,2),
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    approved_by UUID REFERENCES app_user(id) ON DELETE SET NULL,
    move_reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS cash_shift_id UUID REFERENCES cash_shift(id) ON DELETE SET NULL;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS tab_id UUID REFERENCES bar_tab(id) ON DELETE SET NULL;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS guest_name VARCHAR(255);
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS opened_by UUID REFERENCES app_user(id) ON DELETE SET NULL;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS member_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS discount_source VARCHAR(255);
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS member_discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS tax_total NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS amount_paid NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;
ALTER TABLE bar_order ADD COLUMN IF NOT EXISTS void_reason VARCHAR(255);

ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS item_name_snapshot VARCHAR(255) DEFAULT '';
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS tax_inclusive BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS is_comped BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS station VARCHAR(20) NOT NULL DEFAULT 'KITCHEN';
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS ordered_by UUID REFERENCES app_user(id) ON DELETE SET NULL;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS kitchen_status VARCHAR(20) NOT NULL DEFAULT 'NEW';
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS ready_at TIMESTAMPTZ;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS served_at TIMESTAMPTZ;
ALTER TABLE bar_order_line ADD COLUMN IF NOT EXISTS void_reason VARCHAR(255);

CREATE TABLE IF NOT EXISTS bar_cash_movement (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cash_shift_id UUID NOT NULL REFERENCES cash_shift(id) ON DELETE CASCADE,
    type VARCHAR(3) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_by UUID REFERENCES app_user(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bar_day_close (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_date DATE NOT NULL UNIQUE,
    status VARCHAR(10) NOT NULL DEFAULT 'CLOSED',
    closed_by UUID REFERENCES app_user(id) ON DELETE SET NULL,
    closed_at TIMESTAMPTZ,
    reopened_by UUID REFERENCES app_user(id) ON DELETE SET NULL,
    reopened_at TIMESTAMPTZ,
    reopen_reason VARCHAR(255),
    snapshot JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bar_payment (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bar_order_id UUID NOT NULL REFERENCES bar_order(id) ON DELETE CASCADE,
    method VARCHAR(10) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    tendered NUMERIC(12,2) NOT NULL,
    change_given NUMERIC(12,2) NOT NULL DEFAULT 0,
    reference VARCHAR(255),
    received_by UUID REFERENCES app_user(id) ON DELETE SET NULL,
    cash_shift_id UUID REFERENCES cash_shift(id) ON DELETE SET NULL,
    ledger_payment_id UUID,
    idempotency_key VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);
