// Sample data for CCMS Bar & Café: 12 Tables, 30+ Menu Items, Active Tabs, Initial Orders, Shift & Closing data

import { ClubTable, MenuItem, BarTab, BarOrder, ShiftState, DailyClosingReport } from "./types";

export const initialTables: ClubTable[] = [
  {
    id: "T1",
    number: 1,
    name: "Table 1",
    seats: 4,
    section: "MAIN_BAR",
    status: "OCCUPIED",
    currentOrderId: "ORD-1081",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    activeStaffEditing: undefined,
    occupiedSince: new Date(Date.now() - 32 * 60 * 1000).toISOString(), // 32 mins ago
    readyItemsCount: 2, // "2 ready ✓"
  },
  {
    id: "T2",
    number: 2,
    name: "Table 2",
    seats: 2,
    section: "MAIN_BAR",
    status: "FREE",
  },
  {
    id: "T3",
    number: 3,
    name: "Table 3",
    seats: 4,
    section: "MAIN_BAR",
    status: "OCCUPIED",
    currentOrderId: "ORD-1082",
    waiterName: "Priya Sharma",
    waiterInitials: "PS",
    activeStaffEditing: "Priya is editing",
    occupiedSince: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    readyItemsCount: 0,
  },
  {
    id: "T4",
    number: 4,
    name: "Table 4",
    seats: 6,
    section: "LOUNGE",
    status: "OCCUPIED",
    currentOrderId: "ORD-1083",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    occupiedSince: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    readyItemsCount: 1,
  },
  {
    id: "T5",
    number: 5,
    name: "Table 5",
    seats: 4,
    section: "LOUNGE",
    status: "BILL_REQUESTED",
    currentOrderId: "ORD-1084",
    waiterName: "Vikram Sen",
    waiterInitials: "VS",
    occupiedSince: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    billRequestedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    readyItemsCount: 0,
  },
  {
    id: "T6",
    number: 6,
    name: "Table 6",
    seats: 2,
    section: "LOUNGE",
    status: "FREE",
  },
  {
    id: "T7",
    number: 7,
    name: "Table 7",
    seats: 8,
    section: "TERRACE",
    status: "RESERVED",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
  },
  {
    id: "T8",
    number: 8,
    name: "Table 8",
    seats: 4,
    section: "TERRACE",
    status: "FREE",
  },
  {
    id: "T9",
    number: 9,
    name: "Table 9",
    seats: 4,
    section: "TERRACE",
    status: "OCCUPIED",
    currentOrderId: "ORD-1085",
    waiterName: "Kavita Rao",
    waiterInitials: "KR",
    occupiedSince: new Date(Date.now() - 19 * 60 * 1000).toISOString(),
    readyItemsCount: 3,
  },
  {
    id: "T10",
    number: 10,
    name: "Table 10",
    seats: 2,
    section: "COURTSIDE",
    status: "FREE",
  },
  {
    id: "T11",
    number: 11,
    name: "Table 11",
    seats: 4,
    section: "COURTSIDE",
    status: "OCCUPIED",
    currentOrderId: "ORD-1086",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    occupiedSince: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    readyItemsCount: 0,
  },
  {
    id: "T12",
    number: 12,
    name: "Table 12",
    seats: 6,
    section: "COURTSIDE",
    status: "FREE",
  },
];

export const initialMenuItems: MenuItem[] = [
  // FOOD (Kitchen prep, 5% GST)
  {
    id: "M-101",
    name: "Masala Truffle Fries",
    category: "FOOD",
    station: "KITCHEN",
    price: 240,
    taxRate: 0.05,
    description: "Crispy hand-cut fries dusted with homemade gunpowder masala and white truffle oil.",
    isAvailable: true,
    stockQty: 85,
    reorderLevel: 20,
    popularModifiers: ["Less spicy", "Extra parmesan", "Peri peri dust", "Jain spice mix"],
  },
  {
    id: "M-102",
    name: "Classic Club Sandwich",
    category: "FOOD",
    station: "KITCHEN",
    price: 320,
    taxRate: 0.05,
    description: "Triple-decker toasted sourdough with smoked chicken or grilled paneer, cheddar, fried egg & herb mayo.",
    isAvailable: true,
    stockQty: 42,
    reorderLevel: 15,
    popularModifiers: ["Paneer option", "Chicken option", "Brown bread", "No mayo", "Extra toasted"],
  },
  {
    id: "M-103",
    name: "Paneer Tikka Kathi Roll",
    category: "FOOD",
    station: "KITCHEN",
    price: 280,
    taxRate: 0.05,
    description: "Tandoor charred cottage cheese rolled in flaky laccha paratha with mint chutney and pickled onions.",
    isAvailable: true,
    stockQty: 30,
    reorderLevel: 10,
    popularModifiers: ["Less onion", "Extra green chutney", "Double cheese", "Mild spice"],
  },
  {
    id: "M-104",
    name: "Wood-Fired Margherita Pizza",
    category: "FOOD",
    station: "KITCHEN",
    price: 490,
    taxRate: 0.05,
    description: "San Marzano plum tomato sauce, fresh buffalo mozzarella, virgin olive oil and sweet basil.",
    isAvailable: true,
    stockQty: 25,
    reorderLevel: 8,
    popularModifiers: ["Crispy crust", "Extra basil", "Add jalapeños", "Garlic oil drizzle"],
  },
  {
    id: "M-105",
    name: "Pepperoni & Hot Honey Pizza",
    category: "FOOD",
    station: "KITCHEN",
    price: 580,
    taxRate: 0.05,
    description: "Artisan pork pepperoni, fior di latte mozzarella, chilli flakes and hot infused wild honey.",
    isAvailable: true,
    stockQty: 18,
    reorderLevel: 5,
    popularModifiers: ["Extra honey", "Well done crust", "Chilli flakes on side"],
  },
  {
    id: "M-106",
    name: "Wild Mushroom Bruschetta",
    category: "FOOD",
    station: "KITCHEN",
    price: 360,
    taxRate: 0.05,
    description: "Shiitake and button mushrooms in garlic thyme butter on grilled rustic baguette. (86'D TODAY)",
    isAvailable: false, // 86'd item!
    stockQty: 0,
    reorderLevel: 10,
    popularModifiers: ["Without garlic", "Extra thyme"],
  },
  {
    id: "M-107",
    name: "Butter Garlic Prawns",
    category: "FOOD",
    station: "KITCHEN",
    price: 620,
    taxRate: 0.05,
    description: "Tiger prawns tossed in clarified butter, roasted garlic slivers, parsley and bird's eye chilli.",
    isAvailable: true,
    stockQty: 12,
    reorderLevel: 6,
    popularModifiers: ["Mild spice", "Extra garlic bread", "Lime wedge"],
  },
  {
    id: "M-108",
    name: "High-Protein Chicken Rice Bowl",
    category: "FOOD",
    station: "KITCHEN",
    price: 390,
    taxRate: 0.05,
    description: "Grilled herb breast, brown basmati rice, steamed edamame, avocado, and tahini drizzle.",
    isAvailable: true,
    stockQty: 35,
    reorderLevel: 10,
    popularModifiers: ["No avocado", "Extra protein (+₹120)", "Low carb / no rice"],
  },

  // SNACKS (Kitchen / Bar fast items, 5% GST)
  {
    id: "M-201",
    name: "Loaded Nachos Supreme",
    category: "SNACKS",
    station: "KITCHEN",
    price: 340,
    taxRate: 0.05,
    description: "Stoneground corn chips, melted gouda & queso, refried beans, pico de gallo and fresh guacamole.",
    isAvailable: true,
    stockQty: 50,
    reorderLevel: 15,
    popularModifiers: ["Jalapeños on side", "Double cheese", "Sour cream on side"],
  },
  {
    id: "M-202",
    name: "Crispy Calamari Rings",
    category: "SNACKS",
    station: "KITCHEN",
    price: 440,
    taxRate: 0.05,
    description: "Tender semolina crusted squid rings with caper tartar dip and charred lemon.",
    isAvailable: true,
    stockQty: 20,
    reorderLevel: 8,
    popularModifiers: ["Extra tartar sauce", "Spicy paprika dust"],
  },
  {
    id: "M-203",
    name: "Chilli Cheese Garlic Toast",
    category: "SNACKS",
    station: "KITCHEN",
    price: 210,
    taxRate: 0.05,
    description: "Toasted baguette slices topped with cheddar, green chillies and roasted garlic butter.",
    isAvailable: true,
    stockQty: 60,
    reorderLevel: 20,
    popularModifiers: ["Less chilli", "Extra crispy", "Jain prep"],
  },
  {
    id: "M-204",
    name: "Steamed Edamame with Sea Salt",
    category: "SNACKS",
    station: "KITCHEN",
    price: 290,
    taxRate: 0.05,
    description: "Tender young soybeans in the pod dusted with Maldon sea salt and togarashi seasoning.",
    isAvailable: true,
    stockQty: 40,
    reorderLevel: 12,
    popularModifiers: ["No spice / plain salt", "Truffle salt upgrade"],
  },
  {
    id: "M-205",
    name: "Spiced Masala Peanuts",
    category: "SNACKS",
    station: "BAR",
    price: 160,
    taxRate: 0.05,
    description: "Crunchy roasted peanuts with diced onions, tomatoes, coriander and fresh lime juice.",
    isAvailable: true,
    stockQty: 110,
    reorderLevel: 30,
    popularModifiers: ["No raw onion", "Extra spicy", "Double lime"],
  },

  // SOFT DRINKS & COFFEE (Bar station, 5% / 18% GST)
  {
    id: "M-301",
    name: "Cold Brew Vietnamese Coffee",
    category: "SOFT_DRINKS",
    station: "BAR",
    price: 220,
    taxRate: 0.05,
    description: "16-hour steeped single-origin Chikmagalur Arabica coffee over condensed milk and ice.",
    isAvailable: true,
    stockQty: 45,
    reorderLevel: 15,
    popularModifiers: ["Oat milk substitute", "Less sweet", "Extra shot (+₹60)", "Black / no milk"],
  },
  {
    id: "M-302",
    name: "Matcha Iced Latte",
    category: "SOFT_DRINKS",
    station: "BAR",
    price: 260,
    taxRate: 0.05,
    description: "Uji ceremonial grade green tea whisked with chilled almond milk and agave nectar.",
    isAvailable: true,
    stockQty: 30,
    reorderLevel: 10,
    popularModifiers: ["Almond milk", "Oat milk", "Sugar-free syrup"],
  },
  {
    id: "M-303",
    name: "Fresh Watermelon & Mint Cooler",
    category: "SOFT_DRINKS",
    station: "BAR",
    price: 190,
    taxRate: 0.05,
    description: "Cold-pressed fresh watermelon juice muddled with garden mint, rock salt and lime.",
    isAvailable: true,
    stockQty: 55,
    reorderLevel: 20,
    popularModifiers: ["No added sugar", "Extra ice", "Pinch of black salt"],
  },
  {
    id: "M-304",
    name: "Electrolyte Coconut Hydration",
    category: "SOFT_DRINKS",
    station: "BAR",
    price: 180,
    taxRate: 0.05,
    description: "Fresh tender coconut water charged with pink Himalayan salt, chia seeds and lime essence.",
    isAvailable: true,
    stockQty: 40,
    reorderLevel: 15,
    popularModifiers: ["Chilled without ice", "Extra chia"],
  },
  {
    id: "M-305",
    name: "San Pellegrino Sparkling (500ml)",
    category: "SOFT_DRINKS",
    station: "BAR",
    price: 250,
    taxRate: 0.18,
    description: "Natural Italian sparkling mineral water served chilled with lemon wedge.",
    isAvailable: true,
    stockQty: 70,
    reorderLevel: 25,
    popularModifiers: ["Lemon slice", "Cucumber slice"],
  },
  {
    id: "M-306",
    name: "Kombucha Ginger Fizz",
    category: "SOFT_DRINKS",
    station: "BAR",
    price: 230,
    taxRate: 0.05,
    description: "Locally brewed live probiotic tea infused with crushed organic ginger and lemongrass.",
    isAvailable: true,
    stockQty: 24,
    reorderLevel: 10,
    popularModifiers: ["Room temperature", "Served on ice"],
  },

  // BEVERAGES & COCKTAILS (Bar station, 18% GST)
  {
    id: "M-401",
    name: "Court-Side Gin & Tonic",
    category: "BEVERAGES",
    station: "BAR",
    price: 450,
    taxRate: 0.18,
    isAlcoholic: true,
    description: "Stranger & Sons Indian craft gin, artisanal elderflower tonic, dehydrated grapefruit wheel.",
    isAvailable: true,
    stockQty: 48,
    reorderLevel: 12,
    popularModifiers: ["Cucumber ribbon", "Extra tonic", "Pink peppercorns"],
  },
  {
    id: "M-402",
    name: "Smoked Oak Bourbon Old Fashioned",
    category: "BEVERAGES",
    station: "BAR",
    price: 520,
    taxRate: 0.18,
    isAlcoholic: true,
    description: "Woodford Reserve bourbon, Angostura aromatic bitters, turbinado cane sugar, orange peel oils.",
    isAvailable: true,
    stockQty: 32,
    reorderLevel: 8,
    popularModifiers: ["Sweet version", "Dry version", "Flamed orange twist"],
  },
  {
    id: "M-403",
    name: "Bira 91 White Draft Pint (500ml)",
    category: "BEVERAGES",
    station: "BAR",
    price: 340,
    taxRate: 0.18,
    isAlcoholic: true,
    description: "Delicious wheat beer with low bitterness and hints of coriander and orange peel from the tap.",
    isAvailable: true,
    stockQty: 120,
    reorderLevel: 40,
    popularModifiers: ["Chilled mug", "Pitcher (1.5L) upgrade (+₹580)"],
  },
  {
    id: "M-404",
    name: "Corona Extra with Lime (330ml)",
    category: "BEVERAGES",
    station: "BAR",
    price: 380,
    taxRate: 0.18,
    isAlcoholic: true,
    description: "Crisp Mexican lager served ice-cold with a fresh lime wedge inserted in the neck.",
    isAvailable: true,
    stockQty: 85,
    reorderLevel: 24,
    popularModifiers: ["Double lime", "Salted rim"],
  },
  {
    id: "M-405",
    name: "Aperol Spritz Veneziano",
    category: "BEVERAGES",
    station: "BAR",
    price: 480,
    taxRate: 0.18,
    isAlcoholic: true,
    description: "Aperol aperitivo, dry Italian Prosecco, splash of club soda over cubed ice with orange slice.",
    isAvailable: true,
    stockQty: 30,
    reorderLevel: 10,
    popularModifiers: ["Light Aperol", "Extra Prosecco", "Green olive garnish"],
  },
  {
    id: "M-406",
    name: "Fratelli Sette Cabernet Blend (Glass)",
    category: "BEVERAGES",
    station: "BAR",
    price: 650,
    taxRate: 0.18,
    isAlcoholic: true,
    description: "Premium barrel-aged reserve red wine from Akluj estate with notes of dark berries and vanilla.",
    isAvailable: true,
    stockQty: 18,
    reorderLevel: 6,
    popularModifiers: ["Cellar temp (16°C)", "Chilled glass"],
  },
  {
    id: "M-407",
    name: "Spicy Picante Tequila Margarita",
    category: "BEVERAGES",
    station: "BAR",
    price: 490,
    taxRate: 0.18,
    isAlcoholic: true,
    description: "100% Blue Agave Reposado tequila, fresh lime juice, organic agave nectar, coriander and jalapeño.",
    isAvailable: true,
    stockQty: 26,
    reorderLevel: 10,
    popularModifiers: ["Tajin rim", "Extra spicy", "No salt rim"],
  },
];

export const initialOpenTabs: BarTab[] = [
  {
    id: "TAB-01",
    tabNumber: 1,
    name: "Vikramaditya Singhania",
    memberId: "M-1002",
    memberName: "Vikramaditya Singhania",
    memberTier: "PLATINUM",
    memberPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    openedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    activeTableIds: ["T4"],
    runningTotal: 3840,
    creditLimit: 15000,
    status: "OPEN",
    orders: [],
  },
  {
    id: "TAB-02",
    tabNumber: 2,
    name: "Ananya Birla",
    memberId: "M-1004",
    memberName: "Ananya Birla",
    memberTier: "GOLD",
    memberPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    openedAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    activeTableIds: ["T1"],
    runningTotal: 1950,
    creditLimit: 10000,
    status: "OPEN",
    orders: [],
  },
  {
    id: "TAB-03",
    tabNumber: 3,
    name: "Devansh Mehta",
    memberId: "M-1009",
    memberName: "Devansh Mehta",
    memberTier: "SILVER",
    openedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    activeTableIds: ["T9"],
    runningTotal: 2780,
    creditLimit: 5000,
    status: "OPEN",
    orders: [],
  },
  {
    id: "TAB-04",
    tabNumber: 4,
    name: "Rohan Kapoor",
    memberId: "M-1015",
    memberName: "Rohan Kapoor",
    memberTier: "GOLD",
    openedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    activeTableIds: [],
    runningTotal: 1120,
    creditLimit: 8000,
    status: "OPEN",
    orders: [],
  },
];

export const initialOrders: BarOrder[] = [
  // Order for Table 1 (Occupied, 2 ready)
  {
    id: "ORD-1081",
    orderNumber: 1081,
    tableId: "T1",
    tabId: "TAB-02",
    destination: { type: "TABLE", targetId: "T1" },
    customer: {
      memberId: "M-1004",
      name: "Ananya Birla",
      tier: "GOLD",
      discountPercent: 15,
      phone: "+91 98201 44552",
    },
    waiterId: "STF-02",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    items: [
      {
        lineId: "L-101",
        menuItemId: "M-101",
        name: "Masala Truffle Fries",
        price: 240,
        taxRate: 0.05,
        quantity: 2,
        station: "KITCHEN",
        status: "READY", // READY on KDS
        notes: "less spicy",
        modifiers: ["Less spicy"],
        sentAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
        readyAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-102",
        menuItemId: "M-401",
        name: "Court-Side Gin & Tonic",
        price: 450,
        taxRate: 0.18,
        quantity: 2,
        station: "BAR",
        status: "READY", // READY on KDS
        notes: "extra tonic",
        modifiers: ["Cucumber ribbon"],
        sentAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        readyAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-103",
        menuItemId: "M-104",
        name: "Wood-Fired Margherita Pizza",
        price: 490,
        taxRate: 0.05,
        quantity: 1,
        station: "KITCHEN",
        status: "PREPARING",
        modifiers: ["Crispy crust"],
        sentAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 1870,
    discountAmount: 280.5,
    discountDescription: "Member discount (Gold 15%)",
    taxAmount: 184.2,
    total: 1774,
    createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },

  // Order for Table 3 (Table occupied, Priya editing)
  {
    id: "ORD-1082",
    orderNumber: 1082,
    tableId: "T3",
    destination: { type: "TABLE", targetId: "T3" },
    customer: {
      memberId: "M-1011",
      name: "Pratham Shah",
      tier: "GOLD",
      discountPercent: 15,
      phone: "+91 99300 22119",
    },
    waiterId: "STF-04",
    waiterName: "Priya Sharma",
    waiterInitials: "PS",
    items: [
      {
        lineId: "L-201",
        menuItemId: "M-102",
        name: "Classic Club Sandwich",
        price: 320,
        taxRate: 0.05,
        quantity: 1,
        station: "KITCHEN",
        status: "PREPARING",
        modifiers: ["Chicken option", "Brown bread"],
        sentAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-202",
        menuItemId: "M-301",
        name: "Cold Brew Vietnamese Coffee",
        price: 220,
        taxRate: 0.05,
        quantity: 2,
        station: "BAR",
        status: "NEW",
        modifiers: ["Less sweet"],
      },
    ],
    subtotal: 760,
    discountAmount: 114,
    discountDescription: "Member discount (Gold 15%)",
    taxAmount: 43.6,
    total: 690,
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
  },

  // Order for Table 4 (Occupied, high ticket lounge table)
  {
    id: "ORD-1083",
    orderNumber: 1083,
    tableId: "T4",
    tabId: "TAB-01",
    destination: { type: "TABLE", targetId: "T4" },
    customer: {
      memberId: "M-1002",
      name: "Vikramaditya Singhania",
      tier: "PLATINUM",
      discountPercent: 20,
      phone: "+91 98111 88990",
    },
    waiterId: "STF-02",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    items: [
      {
        lineId: "L-301",
        menuItemId: "M-402",
        name: "Smoked Oak Bourbon Old Fashioned",
        price: 520,
        taxRate: 0.18,
        quantity: 3,
        station: "BAR",
        status: "SERVED",
        modifiers: ["Flamed orange twist"],
        sentAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        servedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-302",
        menuItemId: "M-107",
        name: "Butter Garlic Prawns",
        price: 620,
        taxRate: 0.05,
        quantity: 2,
        station: "KITCHEN",
        status: "READY",
        modifiers: ["Extra garlic bread"],
        sentAt: new Date(Date.now() - 26 * 60 * 1000).toISOString(),
        readyAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-303",
        menuItemId: "M-105",
        name: "Pepperoni & Hot Honey Pizza",
        price: 580,
        taxRate: 0.05,
        quantity: 1,
        station: "KITCHEN",
        status: "PREPARING",
        sentAt: new Date(Date.now() - 16 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 3380,
    discountAmount: 676,
    discountDescription: "Member discount (Platinum 20%)",
    taxAmount: 342.4,
    total: 3046,
    createdAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },

  // Order for Table 5 (Bill Requested)
  {
    id: "ORD-1084",
    orderNumber: 1084,
    tableId: "T5",
    destination: { type: "TABLE", targetId: "T5" },
    customer: {
      memberId: "M-1020",
      name: "Suresh Narayanan",
      tier: "SILVER",
      discountPercent: 8,
      phone: "+91 97233 44556",
    },
    waiterId: "STF-07",
    waiterName: "Vikram Sen",
    waiterInitials: "VS",
    items: [
      {
        lineId: "L-401",
        menuItemId: "M-403",
        name: "Bira 91 White Draft Pint (500ml)",
        price: 340,
        taxRate: 0.18,
        quantity: 4,
        station: "BAR",
        status: "SERVED",
        modifiers: ["Chilled mug"],
        sentAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
        servedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-402",
        menuItemId: "M-201",
        name: "Loaded Nachos Supreme",
        price: 340,
        taxRate: 0.05,
        quantity: 2,
        station: "KITCHEN",
        status: "SERVED",
        modifiers: ["Double cheese"],
        sentAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
        servedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-403",
        menuItemId: "M-205",
        name: "Spiced Masala Peanuts",
        price: 160,
        taxRate: 0.05,
        quantity: 2,
        station: "BAR",
        status: "SERVED",
        sentAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        servedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 2360,
    discountAmount: 188.8,
    discountDescription: "Member discount (Silver 8%)",
    taxAmount: 268.4,
    total: 2440,
    isBillRequested: true,
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },

  // Order for Table 9 (Terrace, 3 items ready)
  {
    id: "ORD-1085",
    orderNumber: 1085,
    tableId: "T9",
    tabId: "TAB-03",
    destination: { type: "TABLE", targetId: "T9" },
    customer: {
      memberId: "M-1009",
      name: "Devansh Mehta",
      tier: "SILVER",
      discountPercent: 8,
      phone: "+91 99100 88221",
    },
    waiterId: "STF-05",
    waiterName: "Kavita Rao",
    waiterInitials: "KR",
    items: [
      {
        lineId: "L-501",
        menuItemId: "M-407",
        name: "Spicy Picante Tequila Margarita",
        price: 490,
        taxRate: 0.18,
        quantity: 2,
        station: "BAR",
        status: "READY",
        modifiers: ["Tajin rim", "Extra spicy"],
        sentAt: new Date(Date.now() - 17 * 60 * 1000).toISOString(),
        readyAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-502",
        menuItemId: "M-202",
        name: "Crispy Calamari Rings",
        price: 440,
        taxRate: 0.05,
        quantity: 1,
        station: "KITCHEN",
        status: "READY",
        modifiers: ["Extra tartar sauce"],
        sentAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        readyAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-503",
        menuItemId: "M-303",
        name: "Fresh Watermelon & Mint Cooler",
        price: 190,
        taxRate: 0.05,
        quantity: 1,
        station: "BAR",
        status: "READY",
        sentAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
        readyAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 1610,
    discountAmount: 128.8,
    discountDescription: "Member discount (Silver 8%)",
    taxAmount: 202.6,
    total: 1684,
    createdAt: new Date(Date.now() - 19 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },

  // Order for Table 11 (Courtside, fresh new order)
  {
    id: "ORD-1086",
    orderNumber: 1086,
    tableId: "T11",
    destination: { type: "TABLE", targetId: "T11" },
    customer: {
      name: "Walk-in Guest",
      tier: "NONE",
      discountPercent: 0,
    },
    waiterId: "STF-02",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    items: [
      {
        lineId: "L-601",
        menuItemId: "M-304",
        name: "Electrolyte Coconut Hydration",
        price: 180,
        taxRate: 0.05,
        quantity: 2,
        station: "BAR",
        status: "PREPARING",
        modifiers: ["Chilled without ice"],
        sentAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
      },
      {
        lineId: "L-602",
        menuItemId: "M-203",
        name: "Chilli Cheese Garlic Toast",
        price: 210,
        taxRate: 0.05,
        quantity: 1,
        station: "KITCHEN",
        status: "PREPARING",
        sentAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 570,
    discountAmount: 0,
    taxAmount: 28.5,
    total: 599,
    createdAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    courtBookingRef: "Court 3 - Squash Social",
  },

  // Extra orders for KDS richness: tickets with different age timers!
  // Timer test: >10m ticket (red pulse)
  {
    id: "ORD-1078",
    orderNumber: 1078,
    destination: { type: "COURT", targetId: "Court 2" },
    customer: { name: "Rajesh Varma", tier: "GOLD", discountPercent: 15 },
    waiterId: "STF-02",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    items: [
      {
        lineId: "L-701",
        menuItemId: "M-103",
        name: "Paneer Tikka Kathi Roll",
        price: 280,
        taxRate: 0.05,
        quantity: 2,
        station: "KITCHEN",
        status: "PREPARING",
        notes: "extra green chutney",
        modifiers: ["Extra green chutney"],
        sentAt: new Date(Date.now() - 13 * 60 * 1000).toISOString(), // 13m ago (>10m!)
      },
      {
        lineId: "L-702",
        menuItemId: "M-303",
        name: "Fresh Watermelon & Mint Cooler",
        price: 190,
        taxRate: 0.05,
        quantity: 2,
        station: "BAR",
        status: "PREPARING",
        sentAt: new Date(Date.now() - 13 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 940,
    discountAmount: 141,
    taxAmount: 47,
    total: 846,
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 13 * 60 * 1000).toISOString(),
    courtBookingRef: "Court 2 - Tennis Coaching",
  },

  // Timer test: 5-10m ticket (amber)
  {
    id: "ORD-1080",
    orderNumber: 1080,
    destination: { type: "QUICK", targetId: "Bar Stool 3" },
    customer: { name: "Deepak Patel", tier: "NONE", discountPercent: 0 },
    waiterId: "STF-04",
    waiterName: "Priya Sharma",
    waiterInitials: "PS",
    items: [
      {
        lineId: "L-801",
        menuItemId: "M-404",
        name: "Corona Extra with Lime (330ml)",
        price: 380,
        taxRate: 0.18,
        quantity: 1,
        station: "BAR",
        status: "PREPARING",
        sentAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(), // 7m ago (amber!)
      },
      {
        lineId: "L-802",
        menuItemId: "M-205",
        name: "Spiced Masala Peanuts",
        price: 160,
        taxRate: 0.05,
        quantity: 1,
        station: "BAR",
        status: "PREPARING",
        sentAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 540,
    discountAmount: 0,
    taxAmount: 76.4,
    total: 616,
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
  },

  // Timer test: <5m ticket (white)
  {
    id: "ORD-1087",
    orderNumber: 1087,
    destination: { type: "QUICK", targetId: "Takeaway #04" },
    customer: { name: "Kunal Kapoor", tier: "JUNIOR", discountPercent: 5 },
    waiterId: "STF-02",
    waiterName: "Aarav Mehta",
    waiterInitials: "AM",
    items: [
      {
        lineId: "L-901",
        menuItemId: "M-301",
        name: "Cold Brew Vietnamese Coffee",
        price: 220,
        taxRate: 0.05,
        quantity: 1,
        station: "BAR",
        status: "NEW", // NEW column in KDS
        modifiers: ["Oat milk substitute"],
        sentAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2m ago (white)
      },
      {
        lineId: "L-902",
        menuItemId: "M-101",
        name: "Masala Truffle Fries",
        price: 240,
        taxRate: 0.05,
        quantity: 1,
        station: "KITCHEN",
        status: "NEW", // NEW column in KDS
        sentAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      },
    ],
    subtotal: 460,
    discountAmount: 23,
    taxAmount: 23,
    total: 460,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
];

export const initialShift: ShiftState = {
  shiftId: "SHF-20261003-EVE",
  staffName: "Aarav Mehta",
  staffId: "STF-02",
  clockInTime: "17:02",
  isOpen: true,
  openingFloat: 5000,
  cashMovements: [
    {
      id: "CM-01",
      type: "CASH_IN",
      amount: 5000,
      reason: "Shift opening float from main safe",
      timestamp: "17:02",
    },
    {
      id: "CM-02",
      type: "CASH_OUT",
      amount: 450,
      reason: "Purchase fresh mint and organic limes from vendor",
      timestamp: "18:30",
    },
  ],
};

export const initialDailyClosing: DailyClosingReport = {
  date: "2026-10-03",
  isClosed: false,
  grossSales: 84650,
  memberDiscounts: 8940,
  taxesCollected: 9480,
  netRevenue: 85190,
  totalOrders: 68,
  totalCovers: 142,
  paymentBreakdown: {
    upi: 38400,
    card: 26800,
    cash: 12450,
    tabs: 7540,
  },
  categoryBreakdown: {
    food: 36200,
    beverages: 29800,
    softDrinks: 10450,
    snacks: 8740,
  },
  staffSales: [
    { staffName: "Aarav Mehta", ordersCount: 26, totalSales: 34200, avgPrepTimeMinutes: 8.4 },
    { staffName: "Priya Sharma", ordersCount: 22, totalSales: 28400, avgPrepTimeMinutes: 7.2 },
    { staffName: "Vikram Sen", ordersCount: 12, totalSales: 14600, avgPrepTimeMinutes: 9.1 },
    { staffName: "Kavita Rao", ordersCount: 8, totalSales: 7990, avgPrepTimeMinutes: 6.8 },
  ],
  unsettledTabsCount: 4,
};
