server.port=8081
spring.application.name=bookmycourt

spring.datasource.url=jdbc:postgresql://localhost:5432/bookmycourt
spring.datasource.username=postgres
spring.datasource.password=BookMyCourt@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
