// Sample data for CCMS CRM module (25 realistic leads, quotes, tasks, campaigns)

import type { Lead, LeadActivity, FollowUpTask, Quote, Campaign } from "./types";

export const CRM_OWNERS = [
  { name: "Aarav Mehta", email: "aarav.mehta@championsclub.in", avatar: "AM", role: "Senior Sales Manager" },
  { name: "Kavita Rao", email: "kavita.rao@championsclub.in", avatar: "KR", role: "Membership Consultant" },
  { name: "Vikram Sen", email: "vikram.sen@championsclub.in", avatar: "VS", role: "Corporate Accounts" },
  { name: "Priya Sharma", email: "priya.sharma@championsclub.in", avatar: "PS", role: "Front Desk & Enquiries" },
];

export const INITIAL_LEADS: Lead[] = [
  // ─── STAGE: NEW (5 leads) ───────────────────────────────────────────
  {
    id: "lead-001",
    name: "Rohan Kapadia",
    phone: "+91 98201 12345",
    email: "rohan.kapadia@gmail.com",
    stage: "NEW",
    source: "WEBSITE",
    interest: "Gold Annual Tennis Membership",
    owner: "Aarav Mehta",
    ownerAvatar: "AM",
    estimatedValue: 35000,
    createdAt: "2026-10-03T08:30:00Z",
    nextFollowUp: "2026-10-02T15:00:00Z", // OVERDUE ⏰
    notes: "Submitted website contact form. Enquired about peak hours availability and family discount.",
  },
  {
    id: "lead-002",
    name: "Sunil Shenoy",
    phone: "+91 98450 78210",
    email: "sunil.shenoy@infosys.com",
    companyName: "Infosys Bangalore",
    stage: "NEW",
    source: "WEBSITE",
    interest: "Corporate Squash Package (15 staff)",
    owner: "Vikram Sen",
    ownerAvatar: "VS",
    estimatedValue: 125000,
    createdAt: "2026-10-03T09:15:00Z",
    nextFollowUp: "2026-10-04T11:00:00Z",
    notes: "HR lead exploring sports wellness credits for delivery center staff.",
  },
  {
    id: "lead-003",
    name: "Ananya Deshmukh",
    phone: "+91 97112 45890",
    email: "ananya.d@gmail.com",
    stage: "NEW",
    source: "PHONE",
    interest: "Badminton Weekend Coaching",
    owner: "Priya Sharma",
    ownerAvatar: "PS",
    estimatedValue: 18000,
    createdAt: "2026-10-03T10:00:00Z",
    nextFollowUp: "2026-10-03T17:00:00Z",
    notes: "Called front desk asking about badminton court timings and beginner training clinics.",
  },
  {
    id: "lead-004",
    name: "Varun Malhotra",
    phone: "+91 99200 45678",
    email: "varun.m@outlook.com",
    stage: "NEW",
    source: "WALK_IN",
    interest: "Silver Regular Padel",
    owner: "Kavita Rao",
    ownerAvatar: "KR",
    estimatedValue: 22000,
    createdAt: "2026-10-02T16:00:00Z",
    nextFollowUp: "2026-10-01T14:00:00Z", // OVERDUE ⏰
    notes: "Walked in after evening jog around the park; was impressed with the padel glass courts.",
  },
  {
    id: "lead-005",
    name: "Tanya Nair",
    phone: "+91 98765 43210",
    email: "tanya.nair@zomato.com",
    stage: "NEW",
    source: "WEBSITE",
    interest: "Junior Academy Badminton (<18)",
    owner: "Kavita Rao",
    ownerAvatar: "KR",
    estimatedValue: 14000,
    createdAt: "2026-10-03T07:45:00Z",
    nextFollowUp: "2026-10-04T10:30:00Z",
    notes: "Looking for after-school coaching program for her 12-year-old daughter.",
  },

  // ─── STAGE: CONTACTED (5 leads) ─────────────────────────────────────
  {
    id: "lead-006",
    name: "Priya Deshmukh",
    phone: "+91 98210 65432",
    email: "priya.deshmukh@hdfcbank.com",
    stage: "CONTACTED",
    source: "PHONE",
    interest: "Gold All-Access & Pro Shop Perks",
    owner: "Kavita Rao",
    ownerAvatar: "KR",
    estimatedValue: 35000,
    createdAt: "2026-10-01T11:20:00Z",
    nextFollowUp: "2026-10-02T16:30:00Z", // OVERDUE ⏰
    notes: "Spoke for 15 mins on phone. Requested detailed breakdown of guest pass entitlements.",
  },
  {
    id: "lead-007",
    name: "Aditya Hegde",
    phone: "+91 98860 99887",
    email: "aditya.h@wipro.com",
    stage: "CONTACTED",
    source: "REFERRAL",
    interest: "Tennis Premium Annual",
    owner: "Aarav Mehta",
    ownerAvatar: "AM",
    estimatedValue: 38000,
    createdAt: "2026-09-30T14:10:00Z",
    nextFollowUp: "2026-10-04T15:00:00Z",
    notes: "Referred by Gold Member Dr. Alok Mathur. Needs indoor court access on rainy days.",
  },
  {
    id: "lead-008",
    name: "Meera Patel",
    phone: "+91 98205 11223",
    email: "meera.patel@biocon.com",
    stage: "CONTACTED",
    source: "WEBSITE",
    interest: "Padel Club League + Fitness Pass",
    owner: "Aarav Mehta",
    ownerAvatar: "AM",
    estimatedValue: 28000,
    createdAt: "2026-10-01T09:00:00Z",
    nextFollowUp: "2026-10-05T12:00:00Z",
    notes: "Introductory email sent with schedule of social padel mix-ins.",
  },
  {
    id: "lead-009",
    name: "Karan Johar",
    phone: "+91 98110 33445",
    email: "kjohar@kproductions.in",
    stage: "CONTACTED",
    source: "WALK_IN",
    interest: "Gold All-Access + VIP Lounge",
    owner: "Vikram Sen",
    ownerAvatar: "VS",
    estimatedValue: 45000,
    createdAt: "2026-09-29T17:30:00Z",
    nextFollowUp: "2026-10-02T11:00:00Z", // OVERDUE ⏰
    notes: "Toured the facility with front desk. Wants private coaching rates included in proposal.",
  },
  {
    id: "lead-010",
    name: "Deepak Soni",
    phone: "+91 98991 77665",
    email: "deepak.soni@gmail.com",
    stage: "CONTACTED",
    source: "PHONE",
    interest: "Silver Regular Badminton",
    owner: "Priya Sharma",
    ownerAvatar: "PS",
    estimatedValue: 22000,
    createdAt: "2026-10-02T13:45:00Z",
    nextFollowUp: "2026-10-04T16:00:00Z",
    notes: "Prefers morning slots (6 AM - 8 AM). Sent rate card over WhatsApp.",
  },

  // ─── STAGE: TRIAL_BOOKED (4 leads) ──────────────────────────────────
  {
    id: "lead-011",
    name: "Ananya Iyer",
    phone: "+91 98200 88990",
    email: "ananya.iyer@gmail.com",
    stage: "TRIAL_BOOKED",
    source: "TRIAL",
    interest: "Tennis Trial Session (Intermediate)",
    owner: "Aarav Mehta",
    ownerAvatar: "AM",
    estimatedValue: 35000,
    createdAt: "2026-10-02T10:15:00Z",
    nextFollowUp: "2026-10-04T09:00:00Z",
    trialBookingRef: "TRL-2026-4412",
    notes: "Trial session booked for Court 1 (Clay) on Sunday 9 AM. Racket demo requested.",
  },
  {
    id: "lead-012",
    name: "Kabir Joshi",
    phone: "+91 97170 33221",
    email: "kabir.j@tcs.com",
    stage: "TRIAL_BOOKED",
    source: "TRIAL",
    interest: "Padel Trial Session (Beginner)",
    owner: "Kavita Rao",
    ownerAvatar: "KR",
    estimatedValue: 24000,
    createdAt: "2026-10-01T15:00:00Z",
    nextFollowUp: "2026-10-03T18:00:00Z",
    trialBookingRef: "TRL-2026-5519",
    notes: "First time trying padel with a coworker. Trial session scheduled with Coach Rahul.",
  },
  {
    id: "lead-013",
    name: "Sneha Reddy",
    phone: "+91 99451 22334",
    email: "sneha.reddy@amazon.com",
    stage: "TRIAL_BOOKED",
    source: "TRIAL",
    interest: "Badminton Trial (Advanced)",
    owner: "Priya Sharma",
    ownerAvatar: "PS",
    estimatedValue: 22000,
    createdAt: "2026-09-30T18:30:00Z",
    nextFollowUp: "2026-10-02T17:00:00Z", // OVERDUE ⏰
    trialBookingRef: "TRL-2026-8802",
    notes: "State-level university player looking for competitive sparring partners at the club.",
  },
  {
    id: "lead-014",
    name: "Rishi Chawla",
    phone: "+91 98101 44556",
    email: "rishi.chawla@gmail.com",
    stage: "TRIAL_BOOKED",
    source: "TRIAL",
    interest: "Cricket Net Practice Session",
    owner: "Vikram Sen",
    ownerAvatar: "VS",
    estimatedValue: 15000,
    createdAt: "2026-10-03T06:00:00Z",
    nextFollowUp: "2026-10-05T07:30:00Z",
    trialBookingRef: "TRL-2026-9041",
    notes: "Booked automated bowling machine net session for Saturday morning.",
  },

  // ─── STAGE: QUOTE_SENT (4 leads) ────────────────────────────────────
  {
    id: "lead-015",
    name: "TechCorp Bangalore (Rajesh Nair)",
    phone: "+91 98451 90012",
    email: "rajesh.nair@techcorp.in",
    companyName: "TechCorp Solutions Pvt Ltd",
    stage: "QUOTE_SENT",
    source: "WEBSITE",
    interest: "Corporate Sports Pass (40 Employees)",
    owner: "Vikram Sen",
    ownerAvatar: "VS",
    estimatedValue: 245000,
    createdAt: "2026-09-25T11:00:00Z",
    nextFollowUp: "2026-10-02T14:30:00Z", // OVERDUE ⏰
    notes: "Official corporate quote QTE-2026-081 sent via email with GST compliance sheets.",
  },
  {
    id: "lead-016",
    name: "Divya Iyer",
    phone: "+91 98209 77889",
    email: "divya.iyer@ey.com",
    stage: "QUOTE_SENT",
    source: "REFERRAL",
    interest: "Gold Family Membership (2 Adults + 2 Kids)",
    owner: "Aarav Mehta",
    ownerAvatar: "AM",
    estimatedValue: 78000,
    createdAt: "2026-09-28T16:20:00Z",
    nextFollowUp: "2026-10-04T12:00:00Z",
    notes: "Drafted custom quote with bundled junior academy registration and locker rental.",
  },
  {
    id: "lead-017",
    name: "Siddharth Rao",
    phone: "+91 98801 33441",
    email: "siddharth.r@olaelectric.com",
    stage: "QUOTE_SENT",
    source: "PHONE",
    interest: "Padel Annual League + Custom Pro Racket",
    owner: "Kavita Rao",
    ownerAvatar: "KR",
    estimatedValue: 32000,
    createdAt: "2026-09-29T12:45:00Z",
    nextFollowUp: "2026-10-05T10:00:00Z",
    notes: "Quote QTE-2026-092 emailed with Head Extreme One padel racket included.",
  },
  {
    id: "lead-018",
    name: "Apex Logistics (Arjun Kapoor)",
    phone: "+91 99201 99112",
    email: "arjun.kapoor@apexlogistics.in",
    companyName: "Apex Logistics India",
    stage: "QUOTE_SENT",
    source: "WALK_IN",
    interest: "Inter-Company Badminton Tournament Sponsorship",
    owner: "Vikram Sen",
    ownerAvatar: "VS",
    estimatedValue: 180000,
    createdAt: "2026-09-26T15:10:00Z",
    nextFollowUp: "2026-10-03T16:00:00Z",
    notes: "Sent proposal for 2-day weekend court buyout with F&B catering package.",
  },

  // ─── STAGE: WON (4 leads) ───────────────────────────────────────────
  {
    id: "lead-019",
    name: "Sunita Kulkarni",
    phone: "+91 98203 44556",
    email: "sunita.k@gmail.com",
    stage: "WON",
    source: "REFERRAL",
    interest: "Gold All-Access Annual",
    owner: "Priya Sharma",
    ownerAvatar: "PS",
    estimatedValue: 35000,
    createdAt: "2026-09-20T10:00:00Z",
    convertedMemberId: "MEM-2026-049",
    notes: "Successfully converted at front desk! Registration completed with welcome kit.",
  },
  {
    id: "lead-020",
    name: "Manish Agarwal",
    phone: "+91 98112 55667",
    email: "manish.a@flipkart.com",
    stage: "WON",
    source: "WEBSITE",
    interest: "Silver Regular Padel",
    owner: "Aarav Mehta",
    ownerAvatar: "AM",
    estimatedValue: 22000,
    createdAt: "2026-09-22T14:00:00Z",
    convertedMemberId: "MEM-2026-052",
    notes: "Took trial session on Sep 24 and signed up immediately afterwards.",
  },
  {
    id: "lead-021",
    name: "Novartis Bio Hub (Dr. Sameer Sen)",
    phone: "+91 98860 12890",
    email: "sameer.sen@novartis.com",
    companyName: "Novartis India R&D",
    stage: "WON",
    source: "PHONE",
    interest: "Corporate Squash League (20 Pax)",
    owner: "Vikram Sen",
    ownerAvatar: "VS",
    estimatedValue: 195000,
    createdAt: "2026-09-15T09:30:00Z",
    notes: "Corporate contract signed. GST billing confirmed for 1-year contract.",
  },
  {
    id: "lead-022",
    name: "Nikhil Bansal",
    phone: "+91 99100 22338",
    email: "nikhil.bansal@gmail.com",
    stage: "WON",
    source: "WALK_IN",
    interest: "Gold Tennis + Restringing Pass",
    owner: "Kavita Rao",
    ownerAvatar: "KR",
    estimatedValue: 40000,
    createdAt: "2026-09-18T17:00:00Z",
    convertedMemberId: "MEM-2026-058",
    notes: "Paid via UPI at front desk. Issued member smartcard #7712.",
  },

  // ─── STAGE: LOST (3 leads) ──────────────────────────────────────────
  {
    id: "lead-023",
    name: "Amitav Verma",
    phone: "+91 98204 88776",
    email: "amitav.v@yahoo.com",
    stage: "LOST",
    source: "WALK_IN",
    interest: "Silver Badminton Membership",
    owner: "Vikram Sen",
    ownerAvatar: "VS",
    estimatedValue: 22000,
    createdAt: "2026-09-10T12:00:00Z",
    lostReason: "Joined competitor club closer to residential society in Whitefield.",
    notes: "Followed up twice. Commute time was the deciding factor.",
  },
  {
    id: "lead-024",
    name: "Gauri Mahajan",
    phone: "+91 98450 33229",
    email: "gauri.mahajan@gmail.com",
    stage: "LOST",
    source: "WEBSITE",
    interest: "Junior Tennis Academy",
    owner: "Kavita Rao",
    ownerAvatar: "KR",
    estimatedValue: 14000,
    createdAt: "2026-09-12T15:30:00Z",
    lostReason: "Timing conflict with school evening tuition schedule.",
    notes: "Requested weekend morning slot which is currently at 100% capacity.",
  },
  {
    id: "lead-025",
    name: "Ketan Trivedi",
    phone: "+91 97110 99881",
    email: "ketan.trivedi@outlook.com",
    stage: "LOST",
    source: "PHONE",
    interest: "Gold All-Access Individual",
    owner: "Aarav Mehta",
    ownerAvatar: "AM",
    estimatedValue: 35000,
    createdAt: "2026-09-14T11:00:00Z",
    lostReason: "Pricing out of budget; requested 40% discount which could not be approved.",
    notes: "Informed of corporate tie-up options, declined further consideration.",
  },
];

export const INITIAL_ACTIVITIES: LeadActivity[] = [
  {
    id: "act-001",
    leadId: "lead-001",
    type: "NOTE",
    author: "Aarav Mehta",
    authorRole: "Senior Sales Manager",
    title: "Website Form Intake",
    content: "Customer enquired for peak evening hours (7-9 PM) for Tennis Court 2. Mentioned interest in annual Gold plan with guest passes.",
    createdAt: "2026-10-03T08:35:00Z",
  },
  {
    id: "act-002",
    leadId: "lead-001",
    type: "CALL",
    author: "Aarav Mehta",
    authorRole: "Senior Sales Manager",
    title: "Introductory Call Attempt",
    content: "Called on mobile, line was busy. Left automated SMS with club brochure link.",
    createdAt: "2026-10-03T09:00:00Z",
  },
  {
    id: "act-003",
    leadId: "lead-006",
    type: "CALL",
    author: "Kavita Rao",
    authorRole: "Membership Consultant",
    title: "Discovery Phone Consultation",
    content: "Priya is switching from an older Indiranagar club. Highly interested in our floodlit padel courts and evening bar tab.",
    createdAt: "2026-10-01T11:30:00Z",
  },
  {
    id: "act-004",
    leadId: "lead-006",
    type: "EMAIL",
    author: "Kavita Rao",
    authorRole: "Membership Consultant",
    title: "Sent Gold Membership Brochure",
    content: "Dispatched club presentation and guest pass terms to priya.deshmukh@hdfcbank.com.",
    createdAt: "2026-10-01T12:00:00Z",
  },
  {
    id: "act-005",
    leadId: "lead-015",
    type: "QUOTE_CREATED",
    author: "Vikram Sen",
    authorRole: "Corporate Accounts",
    title: "Corporate Quote QTE-2026-081 Generated",
    content: "Prepared customized proposal for 40 employee quarterly passes @ ₹6,125/pass with complimentary court booking app access.",
    createdAt: "2026-09-25T11:45:00Z",
  },
  {
    id: "act-006",
    leadId: "lead-015",
    type: "QUOTE_SENT",
    author: "Vikram Sen",
    authorRole: "Corporate Accounts",
    title: "Proposal Dispatched via Email",
    content: "PDF quotation sent to rajesh.nair@techcorp.in along with corporate wellness tax-break documentation.",
    createdAt: "2026-09-25T12:30:00Z",
  },
  {
    id: "act-007",
    leadId: "lead-011",
    type: "TRIAL_BOOKED",
    author: "System Engine",
    title: "Trial Booking Confirmed",
    content: "Trial reference TRL-2026-4412 booked for Tennis (Clay Court 1). Hold timer validated.",
    createdAt: "2026-10-02T10:15:00Z",
  },
  {
    id: "act-008",
    leadId: "lead-019",
    type: "CONVERTED",
    author: "Priya Sharma",
    authorRole: "Front Desk & Enquiries",
    title: "Member Registration Finalized",
    content: "Converted to Gold Member MEM-2026-049. ID verification and emergency contacts recorded at front desk.",
    createdAt: "2026-09-20T11:15:00Z",
  },
];

export const INITIAL_TASKS: FollowUpTask[] = [
  {
    id: "task-001",
    leadId: "lead-001",
    title: "Call Rohan regarding family court booking discount",
    dueAt: "2026-10-02T15:00:00Z", // OVERDUE
    completed: false,
    assignedTo: "Aarav Mehta",
    notes: "Offer 10% early registration waiver on annual locker.",
  },
  {
    id: "task-002",
    leadId: "lead-004",
    title: "Send WhatsApp video tour of padel courts",
    dueAt: "2026-10-01T14:00:00Z", // OVERDUE
    completed: false,
    assignedTo: "Kavita Rao",
    notes: "Include video of illuminated glass courts at night.",
  },
  {
    id: "task-003",
    leadId: "lead-006",
    title: "Follow up with Priya on guest pass breakdown",
    dueAt: "2026-10-02T16:30:00Z", // OVERDUE
    completed: false,
    assignedTo: "Kavita Rao",
  },
  {
    id: "task-004",
    leadId: "lead-015",
    title: "Check with Rajesh on TechCorp Finance Approval",
    dueAt: "2026-10-02T14:30:00Z", // OVERDUE
    completed: false,
    assignedTo: "Vikram Sen",
    notes: "PO generation expected by Oct 5.",
  },
  {
    id: "task-005",
    leadId: "lead-002",
    title: "Schedule online demo with Infosys HR team",
    dueAt: "2026-10-04T11:00:00Z",
    completed: false,
    assignedTo: "Vikram Sen",
  },
  {
    id: "task-006",
    leadId: "lead-003",
    title: "Confirm badminton clinic batch availability",
    dueAt: "2026-10-03T17:00:00Z",
    completed: false,
    assignedTo: "Priya Sharma",
  },
  {
    id: "task-007",
    leadId: "lead-011",
    title: "Greet Ananya at front desk for trial session",
    dueAt: "2026-10-04T09:00:00Z",
    completed: false,
    assignedTo: "Aarav Mehta",
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: "qte-001",
    leadId: "lead-015",
    quoteNumber: "QTE-2026-081",
    quoteType: "CORPORATE",
    items: [
      {
        id: "item-1",
        description: "Corporate All-Access Sports Pass (Quarterly per employee)",
        qty: 40,
        rate: 5190.68,
        gstPercent: 18,
        amount: 245000,
      },
      {
        id: "item-2",
        description: "CCMS Corporate Booking App Portal & Dedicated Locker Bank",
        qty: 1,
        rate: 0,
        gstPercent: 18,
        amount: 0,
      },
    ],
    subtotal: 207627.12,
    gstTotal: 37372.88,
    grandTotal: 245000,
    validUntil: "2026-10-25",
    terms: "Payment terms: Net 30 from invoice issuance. Includes GST tax invoice compliant with Indian GSTIN regulations. Peak court access subject to prior slot reservation.",
    status: "SENT",
    createdAt: "2026-09-25T11:45:00Z",
    sentAt: "2026-09-25T12:30:00Z",
  },
  {
    id: "qte-002",
    leadId: "lead-016",
    quoteNumber: "QTE-2026-088",
    quoteType: "MEMBERSHIP",
    items: [
      {
        id: "item-1",
        description: "Gold All-Access Primary Membership (Annual)",
        qty: 1,
        rate: 29661.02,
        gstPercent: 18,
        amount: 35000,
      },
      {
        id: "item-2",
        description: "Gold Spouse Add-on Pass (Annual)",
        qty: 1,
        rate: 18644.07,
        gstPercent: 18,
        amount: 22000,
      },
      {
        id: "item-3",
        description: "Junior Academy Badminton Enrollment (Annual)",
        qty: 2,
        rate: 8898.31,
        gstPercent: 18,
        amount: 21000,
      },
    ],
    subtotal: 66101.71,
    gstTotal: 11898.29,
    grandTotal: 78000,
    validUntil: "2026-10-20",
    terms: "Valid across all 10 championship courts. Unused coaching sessions cannot be carried forward. 15% discount on Pro Shop and Courtside Bar applies immediately.",
    status: "SENT",
    createdAt: "2026-09-28T16:20:00Z",
    sentAt: "2026-09-28T17:00:00Z",
  },
  {
    id: "qte-003",
    leadId: "lead-017",
    quoteNumber: "QTE-2026-092",
    quoteType: "CUSTOM",
    items: [
      {
        id: "item-1",
        description: "Silver Regular Padel Membership (Annual)",
        qty: 1,
        rate: 18644.07,
        gstPercent: 18,
        amount: 22000,
      },
      {
        id: "item-2",
        description: "Head Extreme One Pro Padel Racket & Bag Bundle",
        qty: 1,
        rate: 8474.58,
        gstPercent: 18,
        amount: 10000,
      },
    ],
    subtotal: 27118.65,
    gstTotal: 4881.35,
    grandTotal: 32000,
    validUntil: "2026-10-18",
    terms: "Racket bundle to be collected from Pro Shop on membership start date. 100% manufacturer warranty included.",
    status: "SENT",
    createdAt: "2026-09-29T12:45:00Z",
    sentAt: "2026-09-29T13:10:00Z",
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-001",
    title: "Monsoon Padel & Tennis Early-Bird Invitational",
    channel: "EMAIL",
    segment: {
      tier: "ALL",
      leadStage: "CONTACTED",
      interest: "Tennis / Padel",
    },
    subject: "Claim Your Complimentary 1-Week Trial Pass at Champions Club 🎾",
    content: "Hello {first_name},\n\nWe noticed you enquired about our championship courts recently! As part of our Monsoon Sports Showcase, we would love to invite you for a complimentary 60-minute trial session with our master coach.\n\nUse your exclusive code {offer_code} to reserve your spot online.\n\nWarm regards,\nThe Champions Club Team",
    status: "SENT",
    createdAt: "2026-09-20T10:00:00Z",
    sentAt: "2026-09-21T09:00:00Z",
    recipientCount: 240,
    openCount: 168,
    clickCount: 84,
    conversionCount: 22,
  },
  {
    id: "camp-002",
    title: "Corporate Wellness Autumn League Announcement",
    channel: "EMAIL",
    segment: {
      leadStage: "NEW",
      tier: "Gold",
    },
    subject: "Elevate Team Fitness: Bengaluru Corporate Inter-Company League 2026",
    content: "Hi {first_name},\n\nIs your company ready to compete in Bengaluru's most prestigious corporate racket sports championship? Champions Club is hosting the Corporate Autumn League with ₹2,50,000 in grand prizes, live scoring on LED courtside boards, and catered post-match mixers.\n\nReply to this email or schedule a quick meeting with our Corporate Accounts Director.\n\nBest,\nVikram Sen\nCorporate Accounts Lead",
    status: "SENT",
    createdAt: "2026-09-24T14:30:00Z",
    sentAt: "2026-09-25T11:00:00Z",
    recipientCount: 85,
    openCount: 62,
    clickCount: 39,
    conversionCount: 7,
  },
  {
    id: "camp-003",
    title: "Weekend Junior Coaching Trial Reminder",
    channel: "SMS",
    segment: {
      leadStage: "TRIAL_BOOKED",
      interest: "Junior Academy",
    },
    subject: "Junior Academy Sparring Reminder",
    content: "Hi {first_name}! Quick reminder about junior badminton academy trials this weekend at Champions Club. Bring non-marking sports shoes! Call 080-4920-1100 for directions.",
    status: "SENT",
    createdAt: "2026-09-27T08:00:00Z",
    sentAt: "2026-09-27T09:30:00Z",
    recipientCount: 52,
    openCount: 49,
    clickCount: 28,
    conversionCount: 14,
  },
];
